package com.monitor360.bean;
/**

 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ResponseState implements org.apache.thrift.TEnum {
  StateOk(0),
  StateError(1),
  StateEmpty(2);

  private final int value;

  private ResponseState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ResponseState findByValue(int value) { 
    switch (value) {
      case 0:
        return StateOk;
      case 1:
        return StateError;
      case 2:
        return StateEmpty;
      default:
        return null;
    }
  }
}
